# version format
version: 1.2.1.{build}

# Do not build on tags
skip_tags: true

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
- set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

build_script:
- cd BuildPackage
- Build.bat

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

deploy:
- provider: NuGet
  api_key:
    secure: Ijj27ov2z4KDCJm5vxoNetAOgIluzakEajNLcjrZXApWJZnbPcQDDBmlO1FoZD19
  on:
    branch: develop

- provider: NuGet
  api_key:
    secure: Ijj27ov2z4KDCJm5vxoNetAOgIluzakEajNLcjrZXApWJZnbPcQDDBmlO1FoZD19
  on:
    branch: master
