<<<<<<< HEAD
version: 1.1.0
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
=======
# version format
version: 1.1.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds and use our build.bat file with MSBUILD above
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

>>>>>>> upstream/develop
deploy:
- provider: NuGet
  api_key:
    secure: ouE7tpDB4dawEEQ0ig0uqq2dNEB7J6iDJ7smAPzhlKC/x/p23Txr5MRDqaIQzjYH
  on:
<<<<<<< HEAD
=======
    branch: develop

- provider: NuGet
  api_key:
    secure: ouE7tpDB4dawEEQ0ig0uqq2dNEB7J6iDJ7smAPzhlKC/x/p23Txr5MRDqaIQzjYH
  on:
>>>>>>> upstream/develop
    branch: master