version: 1.1.0
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: ouE7tpDB4dawEEQ0ig0uqq2dNEB7J6iDJ7smAPzhlKC/x/p23Txr5MRDqaIQzjYH
  on:
    branch: master